#############################################################################
# Makefile for building: diffpdf.app/Contents/MacOS/diffpdf
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Dec 2 09:11:39 2013
# Project:  diffpdf.pro
# Template: app
# Command: /usr/local/bin/qmake -spec /usr/local/Cellar/qt/4.8.5/mkspecs/macx-g++ -o Makefile diffpdf.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.5/mkspecs/macx-g++ -I. -I/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/include -I/usr/local/Cellar/poppler/0.24.4/include/poppler/cpp -I/usr/local/Cellar/poppler/0.24.4/include/poppler/qt4 -I. -F/usr/local/Cellar/qt/4.8.5/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.5/lib -L/usr/local/Cellar/qt/4.8.5/lib -lpoppler-qt4 -framework QtGui -L/opt/X11/lib -L/usr/local/Cellar/qt/4.8.5/lib -F/usr/local/Cellar/qt/4.8.5/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.cpp \
		textitem.cpp \
		aboutform.cpp \
		optionsform.cpp \
		helpform.cpp \
		saveform.cpp \
		generic.cpp \
		sequence_matcher.cpp \
		main.cpp \
		lineedit.cpp \
		label.cpp moc_mainwindow.cpp \
		moc_aboutform.cpp \
		moc_optionsform.cpp \
		moc_helpform.cpp \
		moc_saveform.cpp \
		moc_lineedit.cpp \
		moc_label.cpp \
		qrc_resources.cpp

OBJECTS       = mainwindow.o \
		textitem.o \
		aboutform.o \
		optionsform.o \
		helpform.o \
		saveform.o \
		generic.o \
		sequence_matcher.o \
		main.o \
		lineedit.o \
		label.o \
		moc_mainwindow.o \
		moc_aboutform.o \
		moc_optionsform.o \
		moc_helpform.o \
		moc_saveform.o \
		moc_lineedit.o \
		moc_label.o \
		qrc_resources.o

CLI_OBJECTS       = mainwindow.o \
		textitem.o \
		aboutform.o \
		optionsform.o \
		helpform.o \
		saveform.o \
		generic.o \
		sequence_matcher.o \
		lineedit.o \
		label.o \
		moc_mainwindow.o \
		moc_aboutform.o \
		moc_optionsform.o \
		moc_helpform.o \
		moc_saveform.o \
		moc_lineedit.o \
		moc_label.o \
		qrc_resources.o \
		cli.main.o

DIST          = /usr/local/Cellar/qt/4.8.5/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/include_source_dir.prf \
		diffpdf.pro
QMAKE_TARGET  = diffpdf
DESTDIR       = 
TARGET        = diffpdf.app/Contents/MacOS/diffpdf

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile diffpdf.app/Contents/PkgInfo diffpdf.app/Contents/Resources/empty.lproj diffpdf.app/Contents/Info.plist $(TARGET)

diffpdf-cli: mainwindow.cpp cli.main.o $(CLI_OBJECTS)
	$(CXX) $(CXXFLAGS) $(INCPATH) $(LFLAGS)  $(LIBS) $(CLI_OBJECTS) -o diffpdf-cli
 
$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) diffpdf.app/Contents/MacOS/ || $(MKDIR) diffpdf.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: diffpdf.pro  /usr/local/Cellar/qt/4.8.5/mkspecs/macx-g++/qmake.conf /usr/local/Cellar/qt/4.8.5/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.5/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Cellar/qt/4.8.5/mkspecs/macx-g++ -o Makefile diffpdf.pro
/usr/local/Cellar/qt/4.8.5/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.5/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.5/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.5/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.5/mkspecs/common/g++-base.conf:
/usr/local/Cellar/qt/4.8.5/mkspecs/common/g++-macx.conf:
/usr/local/Cellar/qt/4.8.5/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.5/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.5/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Cellar/qt/4.8.5/mkspecs/macx-g++ -o Makefile diffpdf.pro

diffpdf.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) diffpdf.app/Contents || $(MKDIR) diffpdf.app/Contents 
	@$(DEL_FILE) diffpdf.app/Contents/PkgInfo
	@echo "APPL????" >diffpdf.app/Contents/PkgInfo
diffpdf.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) diffpdf.app/Contents/Resources || $(MKDIR) diffpdf.app/Contents/Resources 
	@touch diffpdf.app/Contents/Resources/empty.lproj
	
diffpdf.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) diffpdf.app/Contents || $(MKDIR) diffpdf.app/Contents 
	@$(DEL_FILE) diffpdf.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,diffpdf,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.5/mkspecs/macx-g++/Info.plist.app >diffpdf.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/diffpdf1.0.0 || $(MKDIR) .tmp/diffpdf1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/diffpdf1.0.0/ && $(COPY_FILE) --parents mainwindow.hpp textitem.hpp aboutform.hpp optionsform.hpp helpform.hpp saveform.hpp generic.hpp sequence_matcher.hpp lineedit.hpp label.hpp .tmp/diffpdf1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/diffpdf1.0.0/ && $(COPY_FILE) --parents mainwindow.cpp textitem.cpp aboutform.cpp optionsform.cpp helpform.cpp saveform.cpp generic.cpp sequence_matcher.cpp main.cpp lineedit.cpp label.cpp .tmp/diffpdf1.0.0/ && $(COPY_FILE) --parents diffpdf_cz.ts diffpdf_fr.ts diffpdf_de.ts diffpdf_es.ts .tmp/diffpdf1.0.0/ && (cd `dirname .tmp/diffpdf1.0.0` && $(TAR) diffpdf1.0.0.tar diffpdf1.0.0 && $(COMPRESS) diffpdf1.0.0.tar) && $(MOVE) `dirname .tmp/diffpdf1.0.0`/diffpdf1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/diffpdf1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r diffpdf.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_aboutform.cpp moc_optionsform.cpp moc_helpform.cpp moc_saveform.cpp moc_lineedit.cpp moc_label.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_aboutform.cpp moc_optionsform.cpp moc_helpform.cpp moc_saveform.cpp moc_lineedit.cpp moc_label.cpp
moc_mainwindow.cpp: generic.hpp \
		saveform.hpp \
		mainwindow.hpp
	/usr/local/Cellar/qt/4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.hpp -o moc_mainwindow.cpp

moc_aboutform.cpp: aboutform.hpp
	/usr/local/Cellar/qt/4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ aboutform.hpp -o moc_aboutform.cpp

moc_optionsform.cpp: optionsform.hpp
	/usr/local/Cellar/qt/4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ optionsform.hpp -o moc_optionsform.cpp

moc_helpform.cpp: helpform.hpp
	/usr/local/Cellar/qt/4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ helpform.hpp -o moc_helpform.cpp

moc_saveform.cpp: saveform.hpp
	/usr/local/Cellar/qt/4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ saveform.hpp -o moc_saveform.cpp

moc_lineedit.cpp: lineedit.hpp
	/usr/local/Cellar/qt/4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ lineedit.hpp -o moc_lineedit.cpp

moc_label.cpp: label.hpp
	/usr/local/Cellar/qt/4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ label.hpp -o moc_label.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		diffpdf_cz.qm \
		help_cz.html \
		help_fr.html \
		images/icon.png \
		help_de.html \
		help.html \
		diffpdf_de.qm \
		diffpdf_fr.qm \
		images/right.png \
		images/left.png
	/usr/local/Cellar/qt/4.8.5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

mainwindow.o: mainwindow.cpp aboutform.hpp \
		generic.hpp \
		helpform.hpp \
		label.hpp \
		lineedit.hpp \
		optionsform.hpp \
		mainwindow.hpp \
		saveform.hpp \
		sequence_matcher.hpp \
		textitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

textitem.o: textitem.cpp textitem.hpp \
		generic.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textitem.o textitem.cpp

aboutform.o: aboutform.cpp aboutform.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutform.o aboutform.cpp

optionsform.o: optionsform.cpp generic.hpp \
		optionsform.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsform.o optionsform.cpp

helpform.o: helpform.cpp helpform.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpform.o helpform.cpp

saveform.o: saveform.cpp saveform.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saveform.o saveform.cpp

generic.o: generic.cpp generic.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generic.o generic.cpp

sequence_matcher.o: sequence_matcher.cpp sequence_matcher.hpp \
		generic.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequence_matcher.o sequence_matcher.cpp

main.o: main.cpp mainwindow.hpp \
		generic.hpp \
		saveform.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

lineedit.o: lineedit.cpp generic.hpp \
		lineedit.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lineedit.o lineedit.cpp

label.o: label.cpp generic.hpp \
		label.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o label.o label.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_aboutform.o: moc_aboutform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutform.o moc_aboutform.cpp

moc_optionsform.o: moc_optionsform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsform.o moc_optionsform.cpp

moc_helpform.o: moc_helpform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpform.o moc_helpform.cpp

moc_saveform.o: moc_saveform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_saveform.o moc_saveform.cpp

moc_lineedit.o: moc_lineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lineedit.o moc_lineedit.cpp

moc_label.o: moc_label.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_label.o moc_label.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

cli.main.o: cli.main.cpp \
			mainwindow.hpp \
			generic.hpp \
			saveform.hpp
	
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cli.main.o cli.main.cpp
 
####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

